<?php /** @var $block \MR\PartPay\Block\Error */ ?>

<p>Error: <?php echo htmlentities($block->getError()) ?> </p>
<?php if($block->getShowContinueButton()) :?>
<div class="actions-toolbar">
	<div class="primary">
		<a class="action primary continue"
			href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
	</div>
</div>

<?php endif;?>

