
<?php
/**
 * @see MR_PartPay_Block_PartPay_Info
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle())?>

<?php $_displayKeys = array("CardName");
$_nameMapping = [
    "CardName" => "Payment Type"
];
?>

<?php if ($_specificInfo = $block->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>

	<?php if(strtotime($_label)):?>
		<tr>
		<td colspan="3"><?php echo $block->escapeHtml($_label)?>:</td>
	</tr>
		
		<?php foreach ($_value as $_subKey => $_subValue):?>
		    <?php if(!in_array($_subKey, $_displayKeys)):?>
		      <?php continue;?>
	        <?php endif;?>
			<tr>
		<td></td>
		<td><?php echo $block->escapeHtml($_nameMapping[$_subKey])?>:</td>
		<td><?php echo nl2br(implode($block->getValueAsArray($_subValue, true), "\n"))?></td>
	</tr>
		<?php endforeach; ?>
	<?php else: ?>
	    <?php if(!in_array($_label, $_displayKeys)):?>
	      <?php continue;?>
        <?php endif;?>
	<tr>
		<td><?php echo $block->escapeHtml($_nameMapping[$_label])?>:</td>
		<td colspan="2"><?php echo nl2br(implode($block->getValueAsArray($_value, true), "\n"))?></td>
	</tr>
	<?php endif;?>
<?php endforeach; ?>
</table>
<?php endif;?>

<?php echo $block->getChildHtml()?>
