<?php /** @var $block \PaymentExpress\PxPay2\Block\Redirect */ ?>
<?php if($block->getSuccess()) :?>
<p>You will be redirected to the PxPay2 website in a few seconds</p>

<form action="<?php echo $block->getRedirectUrl() ?>" method="get"
	id="paymentexpress_redirect_form">
	<input id="paymentexpress_redirect" type="submit"
		value="Click here if you are not redirected within 10 seconds..." />
</form>

<script type="text/javascript">
    	document.getElementById("paymentexpress_redirect_form").submit();
    </script>
<?php else: ?>
<p><?php echo htmlentities($block->getError()) ?> </p>
<?php if($block->getShowContinueButton()) :?>
<div class="actions-toolbar">
	<div class="primary">
		<a class="action primary continue"
			href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
	</div>
</div>
<?php endif;?>
	
<?php endif;?>

